apiVersion: v1
kind: Service
metadata:
  name: krok-hook-server
  namespace: krok-system
spec:
  type: ClusterIP
  selector:
    app: krok-controller
  ports:
    - name: http
      port: 9998
      protocol: TCP
      targetPort: hook-server
