apiVersion: v1
kind: Service
metadata:
  name: source-controller
spec:
  type: ClusterIP
  selector:
    app: source-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9999
