apiVersion: v1
kind: Service
metadata:
  name: krok-source-controller
spec:
  type: ClusterIP
  selector:
    app: krok-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: source-server
