apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: krok-o/krok-controller
  newName: ghcr.io/krok-o/krok-controller
  newTag: v0.8.0
patchesStrategicMerge:
- environment_values_patch.yaml
