apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: krok-controller
  name: krok-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krok-controller
  namespace: krok-system
  labels:
    control-plane: krok-controller
spec:
  selector:
    matchLabels:
      control-plane: krok-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: krok-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --hook-base-address=$(PUBLIC_HOST)
        - --source-controller-artifact-base=krok-source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
        - --zap-log-level=4
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PUBLIC_HOST
          value: krok.app
        image: krok-o/krok-controller
        name: manager
        ports:
        - containerPort: 9998
          name: hook-server
          protocol: TCP
        - containerPort: 9999
          name: source-server
          protocol: TCP
        - containerPort: 8081
          name: healthz
          protocol: TCP
        volumeMounts:
          - mountPath: /data
            name: data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: krok-controller
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: data
