---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: krok-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokcommands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.krok.app
  resources:
  - krokevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.krok.app
  resources:
  - krokevents/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokevents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.krok.app
  resources:
  - krokrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokrepositories/status
  verbs:
  - get
  - patch
  - update
