---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - delivery.krok.app
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokcommands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.krok.app
  resources:
  - krokcommands/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokcommands/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.krok.app
  resources:
  - krokevents/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokevents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.krok.app
  resources:
  - krokrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.krok.app
  resources:
  - krokrepositories/status
  verbs:
  - get
  - patch
  - update
