apiVersion: delivery.krok.app/v1alpha1
kind: Command
metadata:
  labels:
    app.kubernetes.io/name: command
    app.kubernetes.io/instance: command-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: command-sample
spec:
  # TODO(user): Add fields here
