apiVersion: delivery.krok.app/v1alpha1
kind: KrokCommand
metadata:
  name: slack-command
  namespace: krok-system
spec:
  enabled: true
  image: krok-hook/slack-notification:v0.0.1
  platforms:
    - github
  args:
    - --something=value
