apiVersion: delivery.krok.app/v1alpha1
kind: Event
metadata:
  labels:
    app.kubernetes.io/name: event
    app.kubernetes.io/instance: event-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: event-sample
spec:
  # TODO(user): Add fields here
