apiVersion: delivery.krok.app/v1alpha1
kind: KrokCommand
metadata:
  labels:
    app.kubernetes.io/name: krokcommand
    app.kubernetes.io/instance: krokcommand-sample
    app.kubernetes.io/part-of: operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: krokcommand-sample
spec:
  # TODO(user): Add fields here
