apiVersion: delivery.krok.app/v1alpha1
kind: KrokRepository
metadata:
  name: repository-sample
  namespace: krok-system
spec:
  authSecretRef:
    name: repository-sample-secret
    namespace: krok-system
  providerTokenSecretRef:
    name: github-secret
    namespace: krok-system
  platform: github
  url: "https://github.com/Skarlso/test"
  events:
    - push
  commands:
    - namespace: krok-system
      name: slack-command
