apiVersion: delivery.krok.app/v1alpha1
kind: KrokRepository
metadata:
  name: repository-sample
spec:
  authSecretRef:
    name: repository-sample-secret
    namespace: default
  providerTokenSecretRef:
    name: github-secret
    namespace: default
  platform: github
  url: "https://github.com/Skarlso/test"
  events:
    - push
    - pull
