apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: krok-controller
    app.kubernetes.io/instance: krok-system
    app.kubernetes.io/part-of: krok
    control-plane: controller
  name: krok-controller
  namespace: krok-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krok-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: krok-controller
    spec:
      containers:
        - args:
            - --hook-base-address={YOUR_IP}:9998
            - --source-controller-artifact-base=krok-source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: localhost:5000/krok-o/krok-controller:v0.0.1
          imagePullPolicy: Always
          name: manager
          ports:
            - containerPort: 9998
              name: hook-server
              protocol: TCP
            - containerPort: 9999
              name: source-server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: tmp
      securityContext:
        fsGroup: 1337
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - emptyDir: {}
          name: data
        - emptyDir: {}
          name: tmp
